system:
        node1:
                privateKey: testnet/keys/node1
                publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAVLVzV9IEDn4+oEM7vNd7gs1Sq3Lgt7/2RQ0s+80bJbpSBUkwmdGcX0Zi5cGRFAAOnSaZfrAJxB+nL6Ofq3VjOmD8kkn4NmKYIRJiSTYbOy/7lwPAXDqMtOGG7JsgMA0EmQrr5U4Q99Wy21vmMw60vH5sHeSLDYm3O7r4JpxLXIlCjWVqxV5lL9XyidwYZbS/Yux26M/XJxl80DSe0tPyrtN0b28XzSqSpdfscZGom3fvVjStjlqkwKhlCPJmT8HBy9KQ/E0ufM1lop850ZarLcrsQV4HCJ2ljcsNO9497vPXxELZLjVRWavISCK1BNEL20UTGcbl/1vGWsVFPUlr
                roles:
                        timer1:
                                type: timer
                                tick: 30
                transports:
                        ssh:
                                address: localhost
                                port: 6020
        node2:
                privateKey: testnet/keys/node2
                publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPqI1iSlFvhrB9ZIvCbuVBGnd0vzUgO+HnqzB8gwb2gOjmUXN13TGjGsyEXvYZvIPHUYHp/A9Ob/afkeA7UiDOrxNMmYco9Aczu63IuEbqS7CWUQVAq84mEhi9j2bQJp7wr1FSAz8Lg1A2jEBYDJo06gvsUJc8UW4ONjgCc4fszCrqvfoZ8reESe2+UaZN+yE+cjpN1Mn1DXwkINRqyXYv6cZHJwAeY04QrwYZWRaQe2BxNzcTo9Kb+emJQupDRx3YKoJuGr+mO6sHDvKY0pAB3ERLKfKKk37X0GK3INBWha4h8RFuTebchP/QVOESC5uTklXtpMGxLxFeYYM0r8T/
                roles:
                        cuckoo:
                                timer: timer1
                        bluetooth-discover:
                transports:
                        ssh:
                                address: localhost
                                port: 6021
        node3:
                privateKey: testnet/keys/node3
                publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQClmIXxWuw60xwwAfRcquSlb1hFxnDwLeBx3ng+4rWRuKoWW6RwF4IYHf3kR44ii8Ov/PBDQZ5rAfAcW/pVix3eXjePCadUzep7NItNAOadofnA24/C9E5rhjQ99uKSzb+jp7L+5zja0VvkrAjkpOwsXHFY5vB7dl7Q5C6qphjdZ5R41RwyHeH0qXyq7szYOCAlt8jsDrlL9F/2/0JvCbN0YLAgwiOf5u2A+m6IVSJ266UF0bWL7V3GCZ52IwUMchUtdU06qCxQeAGJT6wY4SI4SxRjGhK3m8JKQ9xLOzkLNcBs/q+AXtIX7NXKbeijBcGgoFsNYQQK49hytVeNPQTp
                roles:
                        logger:
                                file: testnet/testnet.log
                                clearLog: true
                transports:
                        ssh:
                                address: localhost
                                port: 6022
heartbeat: 1
connectionRetry: 3
